/**
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 */
package leetcode;

import java.util.Arrays;

public class FindTheDifference {
    public char findTheDifference(String s, String t) {

        char[] s1= s.toCharArray();
        char[] t1= t.toCharArray();
        Arrays.sort(s1);
        Arrays.sort(t1);
        char ch = ' ';
        for(int i=0;i<s1.length;i++){
            if(s1[i]!=t1[i]){
                ch=t1[i];
                break;
            }
        }

        return ch!=' '? ch : t1[t1.length-1];
    }
}
